apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast
spec:
  selector:
    matchLabels:
      app: forecast
  replicas: 1
  template:
    metadata:
      name: forecast
      labels:
        app: forecast
    spec:
      containers:
      - image: quay.io/cellgeni/mprofile-web:1.0.0
        imagePullPolicy: IfNotPresent
        name: forecast
        ports:
        - containerPort: 8005
          hostPort: 8005
          name: forecast
        resources:
          requests:
            memory: "128Mi"
            cpu: 0.5
          limits:
            memory: "512Mi"
            cpu: 1
        env:
          - name: MODEL_HOST
            value: http://predictor.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /FORECasT
            port: forecast
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 240
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  selector:
    matchLabels:
      app: predictor
  replicas: 1
  template:
    metadata:
      name: predictor
      labels:
        app: predictor
    spec:
      containers:
      - image: quay.io/felicityallen/selftarget:0.1.9
        imagePullPolicy: IfNotPresent
        name: predictor
        ports:
        - containerPort: 8006
          hostPort: 8006
          name: predictor
        resources:
          requests:
            memory: "1Gi"
            cpu: 1
          limits:
            memory: "4Gi"
            cpu: 4
        env:
        - name: MONGODB_HOST
          value: mongodb://cellgeni:cellgeni@my-release-mongodb.default.svc.cluster.local:27017/wge
        - name: S3_BASE
          value: https://fa9.cog.sanger.ac.uk/
        livenessProbe:
          httpGet:
            path: /ping
            port: predictor
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 240
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: mongo
#spec:
#  selector:
#    matchLabels:
#      app: mongo
#  replicas: 1
#  template:
#    metadata:
#      name: mongo
#      labels:
#        app: mongo
#    spec:
#      containers:
#      - image: quay.io/felicityallen/selftarget:v0.1.6
#        imagePullPolicy: IfNotPresent
#        name: mongo
#        ports:
#        - containerPort: 8006
#          hostPort: 8006
#          name: mongo
#        resources:
#          requests:
#            memory: "1Gi"
#            cpu: 1
#          limits:
#            memory: "4Gi"
#            cpu: 4
#        livenessProbe:
#          httpGet:
#            path: /ping
#            port: mongo
#          initialDelaySeconds: 10
#          timeoutSeconds: 1
#          periodSeconds: 240
