apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast
spec:
  selector:
    matchLabels:
      app: forecast
  replicas: 1
  template:
    metadata:
      name: forecast
      labels:
        app: forecast
    spec:
      containers:
      - image: quay.io/cellgeni/mprofile-web:v0.1.12
        imagePullPolicy: IfNotPresent
        name: forecast
        ports:
        - containerPort: 8005
          hostPort: 8005
          name: forecast
        resources:
          requests:
            memory: "512Mi"
            cpu: 1
          limits:
            memory: "2Gi"
            cpu: 2
        env:
          - name: MODEL_HOST
            value: http://predictor.default.svc.cluster.local
        livenessProbe:
          httpGet:
            path: /FORECasT
            port: forecast
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 240
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  selector:
    matchLabels:
      app: predictor
  replicas: 1
  template:
    metadata:
      name: predictor
      labels:
        app: predictor
    spec:
      containers:
      - image: quay.io/felicityallen/selftarget:v0.1.6
        imagePullPolicy: IfNotPresent
        name: predictor
        ports:
        - containerPort: 8006
          hostPort: 8006
          name: predictor
        resources:
          requests:
            memory: "1Gi"
            cpu: 1
          limits:
            memory: "4Gi"
            cpu: 4
        livenessProbe:
          httpGet:
            path: /ping
            port: predictor
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 240
