apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast
spec:
  selector:
    matchLabels:
      app: forecast
  replicas: 1
  template:
    metadata:
      name: forecast
      labels:
        app: forecast
    spec:
      containers:
      - image: quay.io/cellgeni/mprofile-web:v0.1.8
        imagePullPolicy: IfNotPresent
        name: forecast
        ports:
        - containerPort: 8005
          name: forecast