apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
spec:
  selector:
    matchLabels:
      app: predictor
  replicas: 1
  template:
    metadata:
      name: predictor
      labels:
        app: predictor
    spec:
      containers:
      - image: quay.io/felicityallen/selftarget:v0.1.2
        imagePullPolicy: IfNotPresent
        name: predictor
        ports:
        - containerPort: 8006
          name: predictor
