apiVersion: v1
kind: Service
metadata:
  name: forecast
  labels:
    app: forecast
spec:
  type: NodePort
  ports:
  - port: 8005
    targetPort: forecast
  selector:
    app: forecast
---
apiVersion: v1
kind: Service
metadata:
  name: predictor
  labels:
    app: predictor
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: predictor
  selector:
    app: predictor
