import React from 'react';
import sangerLogo from "../images/sanger_logo.jpg";

class Reference extends React.Component {
    render() {
        return <div className="reference">
            <p>Reference: <a className="dim-link" href="https://www.nature.com/articles/nbt.4317">F. Allen, L.
                Crepaldi et al, "Predicting
                the mutations generated by repair of Cas9-induced double-strand breaks", Nature Biotechnology,
                2019.</a>
            </p>
            <p>For batch mode operation please see <a className="dim-link"
                                                      href="https://github.com/felicityallen/SelfTarget">our
                GitHub</a>.
            </p>
        </div>
    }
}

class SangerFooter extends React.Component {
    render() {
        return <div>
            <img src={sangerLogo} style={{width: "20%"}} alt="Sanger logo" />
            <p>This site is hosted by the <a className="dim-link" href="http://www.sanger.ac.uk/">Wellcome
                Sanger Institute</a><br/>
                <a className="dim-link" href="http://www.sanger.ac.uk/legal/">Terms &amp; Conditions</a> &
                <a className="dim-link" href="http://www.sanger.ac.uk/legal/cookiespolicy.html">Cookies
                    policy</a></p>
        </div>

    }
}


class Footer extends React.Component {
    render() {
        return <footer className="container main-block" id="footer">
            <hr/>
            <Reference/>
            <SangerFooter/>
        </footer>
    }
}

export default Footer;